t=["   ▲   ","  ▲ ▲  "," ▲   ▲ ","▲ ▲ ▲ ▲"]
b="    "
print(b,b,b,t[0],"\n")
print(b,b,b,t[1],"\n")
print(b,b,b,t[2],"\n")
print(b,b,b,t[3],"\n")
print(b,b,t[0]," ",t[0],"\n")
print(b,b,t[1]," ",t[1],"\n")
print(b,b,t[2]," ",t[2],"\n")
print(b,b,t[3]," ",t[3],"\n")
print(b,t[0],b,b," ",t[0],"\n")
print(b,t[1],b,b," ",t[1],"\n")
print(b,t[2],b,b," ",t[2],"\n")
print(b,t[3],b,b," ",t[3],"\n")
print(t[0]," ",t[0]," ",t[0]," ",t[0],"\n")
print(t[1]," ",t[1]," ",t[1]," ",t[1],"\n")
print(t[2]," ",t[2]," ",t[2]," ",t[2],"\n")
print(t[3]," ",t[3]," ",t[3]," ",t[3],"\n")